CREATE TABLE Books (
    BookID INT PRIMARY KEY AUTO_INCREMENT ,
    Image MEDIUMBLOB,
    Title VARCHAR NOT NULL,
    Author VARCHAR NOT NULL,
    Genre VARCHAR NOT NULL,
    Rating INT,
    Price DECIMAL NOT NULL,
    StockQuantity INT NOT NULL DEFAULT 0
);

INSERT INTO Books (Title, Author, Genre, Rating, Price, StockQuantity) VALUES 
('The Chronicles of Narnia: The Lion, the Witch and the Wardrobe', 'C.S. Lewis', 'Fantasy', 4, 21.00, 45),
('Moby-Dick', 'Herman Melville', 'Classic', 3, 26.00, 40),
('Brave New World', 'Aldous Huxley', 'Dystopian', 4, 19.00, 50),
('The Odyssey', 'Homer', 'Epic', 5, 20.00, 35),
('Frankenstein', 'Mary Shelley', 'Gothic', 4, 18.00, 30),
('Wuthering Heights', 'Emily Bronte', 'Gothic', 5, 23.00, 25),
('The Picture of Dorian Gray', 'Oscar Wilde', 'Gothic', 4, 24.00, 20),
('Don Quixote', 'Miguel de Cervantes', 'Classic', 5, 22.00, 55),
('The Count of Monte Cristo', 'Alexandre Dumas', 'Adventure', 5, 28.00, 50),
('Dracula', 'Bram Stoker', 'Gothic', 4, 17.00, 40),
('The Iliad', 'Homer', 'Epic', 5, 19.00, 45),
('Les Misérables', 'Victor Hugo', 'Classic', 5, 27.00, 60),
('Crime and Punishment', 'Fyodor Dostoevsky', 'Psychological Fiction', 4, 25.00, 35),
('One Hundred Years of Solitude', 'Gabriel García Márquez', 'Magical Realism', 5, 30.00, 30),
('War and Peace', 'Leo Tolstoy', 'Historical Fiction', 4, 29.00, 55),
('The Brothers Karamazov', 'Fyodor Dostoevsky', 'Philosophical Fiction', 5, 26.00, 50),
('Anna Karenina', 'Leo Tolstoy', 'Classic', 5, 28.00, 40),
('Jane Eyre', 'Charlotte Bronte', 'Gothic', 4, 23.00, 35),
('The Illiad (Revised)', 'Homer', 'Epic', 5, 20.00, 45),
('The Divine Comedy', 'Dante Alighieri', 'Epic', 5, 24.00, 30),
('The Catcher in the Rye', 'J.D. Salinger', 'Literary Fiction', 4, 20.00, 50),
('To Kill a Mockingbird', 'Harper Lee', 'Classic', 3, 25.00, 30),
('Pride and Prejudice', 'Jane Austen', 'Romance', 5, 15.00, 40),
('1984', 'George Orwell', 'Dystopian', 4, 18.00, 60),
('The Great Gatsby', 'F. Scott Fitzgerald', 'Literary Fiction', 5, 22.00, 55),
('Harry Potter and the Sorcerer''s Stone', 'J.K. Rowling', 'Fantasy', 4, 30.00, 20),
('The Hobbit', 'J.R.R. Tolkien', 'Fantasy', 3, 28.00, 25),
('The Lord of the Rings', 'J.R.R. Tolkien', 'Fantasy', 5, 19.00, 45),
('Animal Farm', 'George Orwell', 'Allegory', 4, 17.00, 35),
('The Da Vinci Code', 'Dan Brown', 'Mystery', 4, 21.00, 50),
('The Old Man and the Sea', 'Ernest Hemingway', 'Classic', 4, 23.00, 45),
('A Tale of Two Cities', 'Charles Dickens', 'Historical Fiction', 5, 21.00, 40),
('The Metamorphosis', 'Franz Kafka', 'Absurdist Fiction', 4, 19.00, 35),
('Gone with the Wind', 'Margaret Mitchell', 'Historical Fiction', 4, 26.00, 30),
('The Sun Also Rises', 'Ernest Hemingway', 'Literary Fiction', 4, 24.00, 25),
('Beloved', 'Toni Morrison', 'Historical Fiction', 5, 28.00, 35),
('Catch-22', 'Joseph Heller', 'Satirical', 5, 22.00, 50),
('The Road', 'Cormac McCarthy', 'Post-Apocalyptic', 4, 20.00, 40),
('Lord of the Flies', 'William Golding', 'Allegory', 5, 18.00, 35),
('The Handmaid''s Tale', 'Margaret Atwood', 'Dystopian', 4, 21.00, 30),
('The Shining', 'Stephen King', 'Horror', 4, 19.00, 25),
('The Girl with the Dragon Tattoo', 'Stieg Larsson', 'Mystery', 4, 23.00, 40),
('The Alchemist', 'Paulo Coelho', 'Philosophical Fiction', 5, 17.00, 45),
('The Road Not Taken', 'Robert Frost', 'Poetry', 5, 15.00, 50),
('The Color Purple', 'Alice Walker', 'Drama', 4, 24.00, 35),
('The Secret Garden', 'Frances Hodgson Burnett', 'Children''s', 5, 18.00, 30),
('Fahrenheit 451', 'Ray Bradbury', 'Dystopian', 4, 20.00, 40),
('The Adventures of Tom Sawyer', 'Mark Twain', 'Adventure', 5, 16.00, 45),
('The Lord of the Rings', 'J.R.R. Tolkien', 'Fantasy', 5, 19.00, 45),
('Slaughterhouse-Five', 'Kurt Vonnegut', 'Science Fiction', 5, 22.00, 40);